version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  frontend:
    build: ./fingesco-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://192.168.1.133:3001
      - REACT_APP_API_KEY=pcldETTDtJ4CQVz9FqlJYHgIvdYP1iXU
    depends_on:
      - endpoint

  endpoint:
    build: ./fingesco-endpoint
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3001
      - API_KEY=pcldETTDtJ4CQVz9FqlJYHgIvdYP1iXU
    depends_on:
      - redis

volumes:
  redis-data: