services:
  - type: web
    name: frontend
    env: node
    plan: free
    preBuildCommand: git submodule update --init --recursive
    buildCommand: npm install --prefix fingesco-frontend
    startCommand: npm start --prefix fingesco-frontend
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: http://endpoint:3001
      - key: REACT_APP_API_KEY
        value: pcldETTDtJ4CQVz9FqlJYHgIvdYP1iXU

  - type: web
    name: endpoint
    env: node
    plan: free
    preBuildCommand: git submodule update --init --recursive
    buildCommand: npm install --prefix fingesco-endpoint
    startCommand: npm start --prefix fingesco-endpoint
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: SERVER_PORT
        value: 3001
      - key: API_KEY
        value: pcldETTDtJ4CQVz9FqlJYHgIvdYP1iXU

  - type: redis
    name: redis
    plan: free
    ipAllowList: []

